#pragma once

#include "Terminal.h"
#include "IOAccess.h"
#include "defines.h"
#include "Descriptors.h"

#define MASTER_DATA 0x21
#define SLAVE_DATA 0xA1

#define MASTER 0x20
#define SLAVE 0xA0
#define EOI 0x20

#define ICW1_INIT 0x10
#define ICW1_EDGE 0x08
#define ICW1_SINGLE 0x02
#define ICW1_ICW4 0x01

#define ICW4_SFNM 0x10
#define ICW4_BUFFER 0x08
#define ICW4_MASTER 0x04
#define ICW4_AROI 0x02
#define ICW4_8086 0x01

#define INT_0 0x8E00
#define INT_3 0xEE00

extern void InterruptWrapper0();
extern void InterruptWrapper1();
extern void InterruptWrapper2();
extern void InterruptWrapper3();
extern void InterruptWrapper4();
extern void InterruptWrapper5();
extern void InterruptWrapper6();
extern void InterruptWrapper7();
extern void InterruptWrapper8();
extern void InterruptWrapper9();
extern void InterruptWrapper10();
extern void InterruptWrapper11();
extern void InterruptWrapper12();
extern void InterruptWrapper13();
extern void InterruptWrapper14();
extern void InterruptWrapper15();
extern void InterruptWrapper16();
extern void InterruptWrapper17();
extern void InterruptWrapper18();
extern void InterruptWrapper19();
extern void InterruptWrapper20();
extern void InterruptWrapper21();
extern void InterruptWrapper22();
extern void InterruptWrapper23();
extern void InterruptWrapper24();
extern void InterruptWrapper25();
extern void InterruptWrapper26();
extern void InterruptWrapper27();
extern void InterruptWrapper28();
extern void InterruptWrapper29();
extern void InterruptWrapper30();
extern void InterruptWrapper31();
extern void InterruptWrapper32();
extern void InterruptWrapper33();
extern void InterruptWrapper34();
extern void InterruptWrapper35();
extern void InterruptWrapper36();
extern void InterruptWrapper37();
extern void InterruptWrapper38();
extern void InterruptWrapper39();
extern void InterruptWrapper39();
extern void InterruptWrapper40();
extern void InterruptWrapper41();
extern void InterruptWrapper42();
extern void InterruptWrapper43();
extern void InterruptWrapper44();
extern void InterruptWrapper45();
extern void InterruptWrapper46();
extern void InterruptWrapper47();
extern void InterruptWrapper48();
extern void InterruptWrapper49();
extern void InterruptWrapper50();
extern void InterruptWrapper51();
extern void InterruptWrapper52();
extern void InterruptWrapper53();
extern void InterruptWrapper54();
extern void InterruptWrapper55();
extern void InterruptWrapper56();
extern void InterruptWrapper57();
extern void InterruptWrapper58();
extern void InterruptWrapper59();
extern void InterruptWrapper60();
extern void InterruptWrapper61();
extern void InterruptWrapper62();
extern void InterruptWrapper63();
extern void InterruptWrapper64();
extern void InterruptWrapper65();
extern void InterruptWrapper66();
extern void InterruptWrapper67();
extern void InterruptWrapper68();
extern void InterruptWrapper69();
extern void InterruptWrapper70();
extern void InterruptWrapper71();
extern void InterruptWrapper72();
extern void InterruptWrapper73();
extern void InterruptWrapper74();
extern void InterruptWrapper75();
extern void InterruptWrapper76();
extern void InterruptWrapper77();
extern void InterruptWrapper78();
extern void InterruptWrapper79();
extern void InterruptWrapper80();
extern void InterruptWrapper81();
extern void InterruptWrapper82();
extern void InterruptWrapper83();
extern void InterruptWrapper84();
extern void InterruptWrapper85();
extern void InterruptWrapper86();
extern void InterruptWrapper87();
extern void InterruptWrapper88();
extern void InterruptWrapper89();
extern void InterruptWrapper90();
extern void InterruptWrapper91();
extern void InterruptWrapper92();
extern void InterruptWrapper93();
extern void InterruptWrapper94();
extern void InterruptWrapper95();
extern void InterruptWrapper96();
extern void InterruptWrapper97();
extern void InterruptWrapper98();
extern void InterruptWrapper99();
extern void InterruptWrapper100();
extern void InterruptWrapper101();
extern void InterruptWrapper102();
extern void InterruptWrapper103();
extern void InterruptWrapper104();
extern void InterruptWrapper105();
extern void InterruptWrapper106();
extern void InterruptWrapper107();
extern void InterruptWrapper108();
extern void InterruptWrapper109();
extern void InterruptWrapper110();
extern void InterruptWrapper111();
extern void InterruptWrapper112();
extern void InterruptWrapper113();
extern void InterruptWrapper114();
extern void InterruptWrapper115();
extern void InterruptWrapper116();
extern void InterruptWrapper117();
extern void InterruptWrapper118();
extern void InterruptWrapper119();
extern void InterruptWrapper120();
extern void InterruptWrapper121();
extern void InterruptWrapper122();
extern void InterruptWrapper123();
extern void InterruptWrapper124();
extern void InterruptWrapper125();
extern void InterruptWrapper126();
extern void InterruptWrapper127();
extern void InterruptWrapper128();
extern void InterruptWrapper129();
extern void InterruptWrapper130();
extern void InterruptWrapper131();
extern void InterruptWrapper132();
extern void InterruptWrapper133();
extern void InterruptWrapper134();
extern void InterruptWrapper135();
extern void InterruptWrapper136();
extern void InterruptWrapper137();
extern void InterruptWrapper138();
extern void InterruptWrapper139();
extern void InterruptWrapper140();
extern void InterruptWrapper141();
extern void InterruptWrapper142();
extern void InterruptWrapper143();
extern void InterruptWrapper144();
extern void InterruptWrapper145();
extern void InterruptWrapper146();
extern void InterruptWrapper147();
extern void InterruptWrapper148();
extern void InterruptWrapper149();
extern void InterruptWrapper150();
extern void InterruptWrapper151();
extern void InterruptWrapper152();
extern void InterruptWrapper153();
extern void InterruptWrapper154();
extern void InterruptWrapper155();
extern void InterruptWrapper156();
extern void InterruptWrapper157();
extern void InterruptWrapper158();
extern void InterruptWrapper159();
extern void InterruptWrapper160();
extern void InterruptWrapper161();
extern void InterruptWrapper162();
extern void InterruptWrapper163();
extern void InterruptWrapper164();
extern void InterruptWrapper165();
extern void InterruptWrapper166();
extern void InterruptWrapper167();
extern void InterruptWrapper168();
extern void InterruptWrapper169();
extern void InterruptWrapper170();
extern void InterruptWrapper171();
extern void InterruptWrapper172();
extern void InterruptWrapper173();
extern void InterruptWrapper174();
extern void InterruptWrapper175();
extern void InterruptWrapper176();
extern void InterruptWrapper177();
extern void InterruptWrapper178();
extern void InterruptWrapper179();
extern void InterruptWrapper180();
extern void InterruptWrapper181();
extern void InterruptWrapper182();
extern void InterruptWrapper183();
extern void InterruptWrapper184();
extern void InterruptWrapper185();
extern void InterruptWrapper186();
extern void InterruptWrapper187();
extern void InterruptWrapper188();
extern void InterruptWrapper189();
extern void InterruptWrapper190();
extern void InterruptWrapper191();
extern void InterruptWrapper192();
extern void InterruptWrapper193();
extern void InterruptWrapper194();
extern void InterruptWrapper195();
extern void InterruptWrapper196();
extern void InterruptWrapper197();
extern void InterruptWrapper198();
extern void InterruptWrapper199();
extern void InterruptWrapper200();
extern void InterruptWrapper201();
extern void InterruptWrapper202();
extern void InterruptWrapper203();
extern void InterruptWrapper204();
extern void InterruptWrapper205();
extern void InterruptWrapper206();
extern void InterruptWrapper207();
extern void InterruptWrapper208();
extern void InterruptWrapper209();
extern void InterruptWrapper210();
extern void InterruptWrapper211();
extern void InterruptWrapper212();
extern void InterruptWrapper213();
extern void InterruptWrapper214();
extern void InterruptWrapper215();
extern void InterruptWrapper216();
extern void InterruptWrapper217();
extern void InterruptWrapper218();
extern void InterruptWrapper219();
extern void InterruptWrapper220();
extern void InterruptWrapper223();
extern void InterruptWrapper224();
extern void InterruptWrapper225();
extern void InterruptWrapper226();
extern void InterruptWrapper227();
extern void InterruptWrapper228();
extern void InterruptWrapper229();
extern void InterruptWrapper230();
extern void InterruptWrapper231();
extern void InterruptWrapper232();
extern void InterruptWrapper233();
extern void InterruptWrapper234();
extern void InterruptWrapper235();
extern void InterruptWrapper236();
extern void InterruptWrapper237();
extern void InterruptWrapper238();
extern void InterruptWrapper239();
extern void InterruptWrapper240();
extern void InterruptWrapper241();
extern void InterruptWrapper242();
extern void InterruptWrapper243();
extern void InterruptWrapper244();
extern void InterruptWrapper245();
extern void InterruptWrapper246();
extern void InterruptWrapper247();
extern void InterruptWrapper248();
extern void InterruptWrapper249();
extern void InterruptWrapper250();
extern void InterruptWrapper251();
extern void InterruptWrapper252();
extern void InterruptWrapper253();
extern void InterruptWrapper254();
extern void InterruptWrapper255();

void InterruptHandler();
void MakeInterruptsWork();
void PICRemap(int offsetM, int offsetS);
void MaskIRQ(unsigned char irq);
void UnmaskIRQ(unsigned char irq);
void AddInterrupt(int number, void (*handler)(), uint dpl);
void AddInterrupts();
